import { NextResponse } from "next/server";
import { and, eq, isNull } from "drizzle-orm";
import { db, schema } from "@/lib/db";
import { requireDbUser } from "@/lib/auth/current-user";
import { parseBody } from "@/lib/api/parse";
import { RegisterDevice } from "@/lib/api/schemas";
import { log } from "@/lib/log";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// POST: register or refresh this device's pubkey for the signed-in user.
// Re-registering the same deviceId rotates the public key (revokes the prior
// row, inserts a new one). Rotation UX in /app/settings calls this endpoint
// with a fresh keypair generated by lib/crypto/keystore.rotateDevice().

export async function POST(req: Request) {
  const me = await requireDbUser();
  const parsed = await parseBody(req, RegisterDevice);
  if (parsed.error) return parsed.error;
  const body = parsed.data;
  const conn = db();
  const pub = Buffer.from(body.publicKey, "base64");

  // Revoke any prior unrevoked row for this user+device
  const revoked = await conn
    .update(schema.deviceKeys)
    .set({ revokedAt: new Date() })
    .where(
      and(
        eq(schema.deviceKeys.userId, me.id),
        eq(schema.deviceKeys.deviceId, body.deviceId),
        isNull(schema.deviceKeys.revokedAt),
      ),
    )
    .returning({ id: schema.deviceKeys.id });

  const [row] = await conn
    .insert(schema.deviceKeys)
    .values({
      userId: me.id,
      deviceId: body.deviceId,
      publicKey: pub,
    })
    .returning({ id: schema.deviceKeys.id });

  log.info("device.registered", {
    userId: me.id,
    deviceId: body.deviceId,
    deviceKeyId: row.id,
    rotated: revoked.length > 0,
    revokedKeyIds: revoked.map((r) => r.id),
  });

  return NextResponse.json({ id: row.id });
}
