import type { SakinahAgentName } from "@/lib/agents/registry";

export type ImprovementStatus = "live" | "active" | "blocked" | "queued";

export type PlatformImprovement = {
  n: number;
  title: string;
  owner: SakinahAgentName | "Sakinah";
  phase: "control" | "service" | "trust" | "verification" | "launch";
  status: ImprovementStatus;
  score: number;
  route: string;
  next: string;
  blocker?: string;
};

export const platformImprovements: readonly PlatformImprovement[] = [
  {
    n: 1,
    title: "Provider readiness control plane",
    owner: "Sabr",
    phase: "control",
    status: "live",
    score: 9,
    route: "/app/readiness",
    next: "Keep every provider promise visible as live, blocked, or optional.",
  },
  {
    n: 2,
    title: "Signed photo access gate",
    owner: "Hafiz",
    phase: "trust",
    status: "live",
    score: 9,
    route: "/api/photos/:id",
    next: "Issue tokens only after mutual interest.",
  },
  {
    n: 3,
    title: "Fifty-item platform execution rail",
    owner: "Sakinah",
    phase: "control",
    status: "active",
    score: 9,
    route: "/app/improvements",
    next: "Use this rail to drive the next autonomous passes.",
  },
  {
    n: 4,
    title: "Clerk webhook completion",
    owner: "Hafiz",
    phase: "verification",
    status: "blocked",
    score: 9,
    route: "/api/webhooks/clerk",
    blocker: "Requires Clerk dashboard endpoint secret.",
    next: "Create endpoint and add CLERK_WEBHOOK_SECRET.",
  },
  {
    n: 5,
    title: "Twilio phone proof",
    owner: "Hafiz",
    phase: "verification",
    status: "blocked",
    score: 8,
    route: "/app/verification",
    blocker: "Requires Twilio Verify credentials.",
    next: "Add Verify service env and expose send/check controls.",
  },
  {
    n: 6,
    title: "Stripe checkout entitlement",
    owner: "Sakinah",
    phase: "launch",
    status: "blocked",
    score: 9,
    route: "/app/billing",
    blocker: "Requires Stripe keys, price, and webhook secret.",
    next: "Set envs, test webhook, then remove billing launch gate.",
  },
  {
    n: 7,
    title: "Private R2 media buckets",
    owner: "Hafiz",
    phase: "trust",
    status: "blocked",
    score: 8,
    route: "/app/readiness",
    blocker: "Requires R2 account and scoped keys.",
    next: "Create private buckets for photo and voice objects.",
  },
  {
    n: 8,
    title: "Voice purge worker",
    owner: "Watim",
    phase: "trust",
    status: "queued",
    score: 8,
    route: "/app/onboarding",
    next: "Add a 24h purge queue for voice drafts.",
  },
  {
    n: 9,
    title: "Salaam quota telemetry",
    owner: "Adil",
    phase: "service",
    status: "active",
    score: 8,
    route: "/api/service/salaam/quota",
    next: "Surface quota history and reset timing on every salaam CTA.",
  },
  {
    n: 10,
    title: "Wali digest cron audit",
    owner: "Sabr",
    phase: "trust",
    status: "active",
    score: 8,
    route: "/api/cron/wali-digest",
    next: "Persist digest run stats without plaintext excerpts.",
  },
  {
    n: 11,
    title: "Profile completeness meter",
    owner: "Hafiz",
    phase: "service",
    status: "queued",
    score: 8,
    route: "/app/onboarding",
    next: "Score public, gated, and family layers before matching.",
  },
  {
    n: 12,
    title: "Discovery hard-gate persistence",
    owner: "Watim",
    phase: "service",
    status: "queued",
    score: 8,
    route: "/app/discovery",
    next: "Save hard gates separately from soft preferences.",
  },
  {
    n: 13,
    title: "No-fake-inventory state",
    owner: "Watim",
    phase: "service",
    status: "live",
    score: 9,
    route: "/app/matches",
    next: "Keep empty-match states explicit until eligible candidates exist.",
  },
  {
    n: 14,
    title: "Match explainability diff",
    owner: "Watim",
    phase: "service",
    status: "queued",
    score: 7,
    route: "/app/matches",
    next: "Show which preference each suggestion satisfies.",
  },
  {
    n: 15,
    title: "Salaam request expiry",
    owner: "Adil",
    phase: "service",
    status: "queued",
    score: 8,
    route: "/app/salaam",
    next: "Expire stale salaams and record Sabr-visible state.",
  },
  {
    n: 16,
    title: "Thread opener suggestions",
    owner: "Adil",
    phase: "service",
    status: "active",
    score: 7,
    route: "/thread/:id",
    next: "Make opener prompts stateful and exportable.",
  },
  {
    n: 17,
    title: "Handoff ceremony checklist",
    owner: "Adil",
    phase: "service",
    status: "active",
    score: 8,
    route: "/thread/:id",
    next: "Require explicit handoff checkpoints before contact exchange.",
  },
  {
    n: 18,
    title: "Observer invite acceptance",
    owner: "Sabr",
    phase: "trust",
    status: "queued",
    score: 8,
    route: "/app/family",
    next: "Add signed invite acceptance and role audit rows.",
  },
  {
    n: 19,
    title: "Observer note boundaries",
    owner: "Sabr",
    phase: "trust",
    status: "queued",
    score: 8,
    route: "/observe/notes",
    next: "Allow private notes while blocking room posting.",
  },
  {
    n: 20,
    title: "Private Watim family channel",
    owner: "Watim",
    phase: "trust",
    status: "active",
    score: 7,
    route: "/observe/ask-watim",
    next: "Persist allowed questions and redact profile-sensitive fields.",
  },
  {
    n: 21,
    title: "Sabr pressure event model",
    owner: "Sabr",
    phase: "trust",
    status: "active",
    score: 9,
    route: "/app/sabr",
    next: "Separate pause, report, observer, and stale-flow events.",
  },
  {
    n: 22,
    title: "Safety reviewer role gate",
    owner: "Sabr",
    phase: "trust",
    status: "live",
    score: 9,
    route: "/admin/sabr",
    next: "Keep admin triage invisible unless role is safety_reviewer.",
  },
  {
    n: 23,
    title: "Audit export coverage",
    owner: "Sabr",
    phase: "trust",
    status: "live",
    score: 8,
    route: "/api/service/audit",
    next: "Add provider readiness and improvement rail to export.",
  },
  {
    n: 24,
    title: "Agent action hash audit",
    owner: "Sabr",
    phase: "trust",
    status: "live",
    score: 8,
    route: "/app/settings/audit",
    next: "Keep prompt and response hashes without room plaintext.",
  },
  {
    n: 25,
    title: "Arabic RTL QA rail",
    owner: "Sakinah",
    phase: "trust",
    status: "active",
    score: 7,
    route: "/trust",
    next: "Run visual smoke for Arabic public routes.",
  },
  {
    n: 26,
    title: "Privacy policy provider table",
    owner: "Sabr",
    phase: "trust",
    status: "queued",
    score: 8,
    route: "/privacy",
    next: "List provider, data class, retention, and launch status.",
  },
  {
    n: 27,
    title: "Account deletion audit receipt",
    owner: "Hafiz",
    phase: "trust",
    status: "queued",
    score: 8,
    route: "/account/delete",
    next: "Return deletion receipt without retaining private content.",
  },
  {
    n: 28,
    title: "Billing portal route",
    owner: "Sakinah",
    phase: "launch",
    status: "queued",
    score: 8,
    route: "/app/billing",
    next: "Add Stripe billing portal once customer IDs exist.",
  },
  {
    n: 29,
    title: "Android Play Billing entitlement",
    owner: "Sakinah",
    phase: "launch",
    status: "blocked",
    score: 9,
    route: "/app/mobile-flow",
    blocker: "Requires Play developer verification and app upload.",
    next: "Use Google Play Billing only for Android in-app access.",
  },
  {
    n: 30,
    title: "iOS entitlement placeholder",
    owner: "Sakinah",
    phase: "launch",
    status: "queued",
    score: 6,
    route: "/app/mobile-flow",
    next: "Keep iOS path documented but defer launch until account exists.",
  },
  {
    n: 31,
    title: "Public trust deep links",
    owner: "Sabr",
    phase: "trust",
    status: "queued",
    score: 7,
    route: "/trust",
    next: "Anchor encryption, photo gate, observer, billing, and AI boundaries.",
  },
  {
    n: 32,
    title: "Family FAQ expansion",
    owner: "Sabr",
    phase: "trust",
    status: "queued",
    score: 7,
    route: "/for-families",
    next: "Answer wali permissions, privacy, and consent questions.",
  },
  {
    n: 33,
    title: "Press-safe overview",
    owner: "Sakinah",
    phase: "launch",
    status: "queued",
    score: 5,
    route: "/trust",
    next: "Write only after provider states stop being mostly blocked.",
  },
  {
    n: 34,
    title: "Referral-free invite proof",
    owner: "Hafiz",
    phase: "trust",
    status: "active",
    score: 7,
    route: "/invite",
    next: "Keep invite flow free of growth tracking claims.",
  },
  {
    n: 35,
    title: "Device-key recovery warning",
    owner: "Adil",
    phase: "trust",
    status: "queued",
    score: 8,
    route: "/app/settings",
    next: "Explain loss, rotation, and recovery without weakening E2E.",
  },
  {
    n: 36,
    title: "Recipient-key freshness",
    owner: "Adil",
    phase: "trust",
    status: "queued",
    score: 8,
    route: "/api/threads/:id/recipient-keys",
    next: "Mark revoked or stale recipient devices before send.",
  },
  {
    n: 37,
    title: "Thread stream pagination",
    owner: "Adil",
    phase: "service",
    status: "queued",
    score: 7,
    route: "/api/threads/:id/stream",
    next: "Add cursor pagination for larger rooms.",
  },
  {
    n: 38,
    title: "Rate-limit evidence panel",
    owner: "Sabr",
    phase: "control",
    status: "queued",
    score: 8,
    route: "/app/settings/audit",
    next: "Show rate-limit state without exposing security internals.",
  },
  {
    n: 39,
    title: "Provider env doctor JSON",
    owner: "Sabr",
    phase: "control",
    status: "queued",
    score: 8,
    route: "scripts/doctor.ts",
    next: "Emit machine-readable readiness for CI and dashboards.",
  },
  {
    n: 40,
    title: "Launch smoke script",
    owner: "Sabr",
    phase: "launch",
    status: "queued",
    score: 9,
    route: "scripts/",
    next: "Smoke public, protected-hidden, and gated-photo routes after deploy.",
  },
  {
    n: 41,
    title: "Bundle regression ledger",
    owner: "Sakinah",
    phase: "control",
    status: "live",
    score: 7,
    route: "scripts/check-bundle-budget.ts",
    next: "Keep each new route under budget.",
  },
  {
    n: 42,
    title: "Playwright authenticated smoke",
    owner: "Sabr",
    phase: "launch",
    status: "queued",
    score: 8,
    route: "tests/e2e",
    next: "Add a test-user flow once test auth creds are stable.",
  },
  {
    n: 43,
    title: "Neon schema drift failfast",
    owner: "Sabr",
    phase: "control",
    status: "live",
    score: 9,
    route: "scripts/check-schema-drift.ts",
    next: "Keep DB drift in CI before production deploys.",
  },
  {
    n: 44,
    title: "Provider missing-copy standard",
    owner: "Sakinah",
    phase: "control",
    status: "queued",
    score: 7,
    route: "/app/readiness",
    next: "Use the same launch-gate language across routes.",
  },
  {
    n: 45,
    title: "Sentry server capture",
    owner: "Sabr",
    phase: "launch",
    status: "blocked",
    score: 7,
    route: "lib/observability.ts",
    blocker: "Requires SENTRY_DSN.",
    next: "Wire server error capture after DSN is set.",
  },
  {
    n: 46,
    title: "PostHog privacy allowlist",
    owner: "Sabr",
    phase: "launch",
    status: "blocked",
    score: 7,
    route: "lib/observability.ts",
    blocker: "Requires POSTHOG_KEY.",
    next: "Track only non-observer, non-plaintext events.",
  },
  {
    n: 47,
    title: "Operational changelog",
    owner: "Sakinah",
    phase: "control",
    status: "queued",
    score: 6,
    route: "/app/engineering",
    next: "Expose shipped platform changes for operator review.",
  },
  {
    n: 48,
    title: "Agent prompt versioning",
    owner: "Watim",
    phase: "control",
    status: "queued",
    score: 8,
    route: "/app/engineering",
    next: "Hash and display prompt versions used for service-state actions.",
  },
  {
    n: 49,
    title: "Data retention ledger",
    owner: "Sabr",
    phase: "trust",
    status: "queued",
    score: 9,
    route: "/trust",
    next: "Make retention explicit for profile, voice, photos, audit, and billing.",
  },
  {
    n: 50,
    title: "Launch cutover checklist",
    owner: "Sakinah",
    phase: "launch",
    status: "queued",
    score: 9,
    route: "/app/improvements",
    next: "Promote only when provider gates and smoke checks are green.",
  },
];

export function getPlatformImprovements() {
  const items = [...platformImprovements].sort((a, b) => a.n - b.n);
  const counts = items.reduce(
    (acc, item) => {
      acc[item.status] += 1;
      return acc;
    },
    { active: 0, blocked: 0, live: 0, queued: 0 } as Record<
      ImprovementStatus,
      number
    >,
  );
  const next = items
    .filter((item) => item.status !== "live")
    .sort((a, b) => b.score - a.score || a.n - b.n)
    .slice(0, 5);
  return {
    counts,
    items,
    next,
    total: items.length,
  };
}
